"""
Specialist generation agents for frontend/backend/ml/docs domains.
"""
from __future__ import annotations

import json
import asyncio
import os
from typing import Dict, Any, List, AsyncGenerator

import httpx

from config.models import OLLAMA_BASE
from config.pools import SPECIALIST_POOLS
from agents.vram_selector import select_model
from agents.file_writer import extract_code_content


MAX_SPECIALIST_MODELS = 4
MAX_SPECIALIST_ATTEMPTS_PER_MODEL = 2


EMERGENCY_TEMPLATES = {
        "package.json": """{
    \"name\": \"generated-app\",
    \"version\": \"0.1.0\",
    \"private\": true,
    \"scripts\": {
        \"start\": \"node app.js\",
        \"dev\": \"node app.js\"
    }
}
""",
        ".gitignore": """node_modules/
dist/
build/
.next/
.venv/
venv/
__pycache__/
*.pyc
*.log
.env
.env.*
""",
        "index.html": """<!doctype html>
<html lang=\"en\">
    <head>
        <meta charset=\"UTF-8\" />
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
        <title>Generated App</title>
        <link rel=\"stylesheet\" href=\"styles.css\" />
    </head>
    <body>
        <main id=\"app\">
            <h1>Generated App</h1>
            <p>Project scaffold was generated with resilience fallback.</p>
        </main>
        <script src=\"app.js\"></script>
    </body>
</html>
""",
        "styles.css": """:root { color-scheme: dark; }
body {
    margin: 0;
    min-height: 100vh;
    display: grid;
    place-items: center;
    font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
    background: #0b0c10;
    color: #f3f4f6;
}
#app {
    max-width: 640px;
    padding: 24px;
    border: 1px solid #2d3440;
    border-radius: 12px;
    background: #111827;
}
""",
        "app.js": """(function () {
    const root = document.getElementById('app');
    if (!root) return;
    const stamp = new Date().toISOString();
    const p = document.createElement('p');
    p.textContent = `Ready at ${stamp}`;
    root.appendChild(p);
})();
""",
        "README.md": """# Generated Project

This project was generated by Cortex.

## Run

1. Install dependencies if required.
2. Start using your runtime tooling.
""",
}


def _build_specialist_system(domain: str) -> str:
    if domain == "frontend":
        return (
            "You are a frontend specialist. Use React functional components, TypeScript types, "
            "responsive layouts, and accessible semantics."
        )
    if domain == "backend":
        return (
            "You are a backend specialist. Prefer async FastAPI/Pydantic patterns with robust "
            "error handling and secure defaults."
        )
    if domain == "ml":
        return (
            "You are an ML specialist. Write reproducible ML/data code and include stable "
            "inference/train conventions where relevant."
        )
    return (
        "You are a docs/config specialist. Produce concise and correct markdown/configuration "
        "files with practical instructions."
    )


async def _generate_once(model: str, system: str, prompt: str, path: str) -> str:
    async with httpx.AsyncClient(timeout=35) as client:
        resp = await client.post(
            f"{OLLAMA_BASE}/api/generate",
            json={
                "model": model,
                "system": system,
                "prompt": prompt,
                "stream": False,
                "options": {"temperature": 0.2, "num_predict": 4096},
            },
        )
        resp.raise_for_status()
        raw = str(resp.json().get("response", ""))
        return extract_code_content(raw, path)


def _candidate_models(domain: str, selected: str) -> List[str]:
    pool = SPECIALIST_POOLS.get(domain, SPECIALIST_POOLS["backend"])
    candidates = [selected, *pool, "qwen2.5-coder:7b", "qwen2.5:7b", "llama3.1:8b"]
    out: List[str] = []
    seen = set()
    for model in candidates:
        key = str(model or "").strip()
        if not key or key in seen:
            continue
        seen.add(key)
        out.append(key)
    return out[:MAX_SPECIALIST_MODELS]


def _generic_emergency_content(path: str) -> str:
    rel = str(path or "").replace("\\", "/").strip()
    lower = rel.lower()

    if lower.endswith(".json"):
        return "{}\n"
    if lower.endswith(".md"):
        return f"# {os.path.basename(rel) or 'Generated File'}\n\nThis file was generated using fallback content.\n"
    if lower.endswith(".html"):
        return (
            "<!doctype html>\n"
            "<html lang=\"en\">\n"
            "  <head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" /><title>Generated</title></head>\n"
            "  <body><main>Generated fallback content.</main></body>\n"
            "</html>\n"
        )
    if lower.endswith(".css"):
        return "/* generated fallback stylesheet */\n"
    if lower.endswith(".js") or lower.endswith(".ts") or lower.endswith(".jsx") or lower.endswith(".tsx"):
        return "// generated fallback script\n"
    if lower.endswith(".py"):
        return "# generated fallback python module\n"
    if lower.endswith(".gitignore"):
        return "# generated fallback ignore file\n"
    return "# generated fallback content\n"


def _emergency_content(path: str) -> str:
    rel = str(path or "").replace("\\", "/").strip().lower()
    base = rel.split("/")[-1]
    return EMERGENCY_TEMPLATES.get(base, _generic_emergency_content(path))


async def run_specialist(
    domain: str,
    file_spec: Dict[str, Any],
    project_name: str,
    task: str,
    project_path: str,
    context_blobs: List[str] | None = None,
) -> Dict[str, Any]:
    rel_path = str(file_spec.get("path", "")).strip()
    purpose = str(file_spec.get("description") or file_spec.get("purpose") or "").strip()
    if not rel_path:
        return {"ok": False, "error": "missing_path", "path": rel_path}

    pool = SPECIALIST_POOLS.get(domain, SPECIALIST_POOLS["backend"])
    try:
        model = await select_model(pool, prefer_quality=True)
    except Exception:
        model = pool[0] if pool else "qwen2.5-coder:7b"
    system = _build_specialist_system(domain)

    extra_context = "\n\n".join(context_blobs or [])
    prompt = (
        f"Project: {project_name}\n"
        f"Task: {task}\n"
        f"File path: {rel_path}\n"
        f"Purpose: {purpose}\n\n"
        "Output ONLY the complete file content for this file. No commentary."
    )
    if extra_context:
        prompt += f"\n\nAdditional context:\n{extra_context}"

    errors: List[str] = []
    content = ""
    used_model = model
    for candidate_model in _candidate_models(domain, model):
        used_model = candidate_model
        for attempt in range(1, MAX_SPECIALIST_ATTEMPTS_PER_MODEL + 1):
            try:
                content = await _generate_once(candidate_model, system, prompt, rel_path)
                if content and len(content.strip()) >= 4:
                    break
                errors.append(f"{candidate_model} attempt {attempt}: empty_content")
            except httpx.HTTPStatusError as exc:
                status = exc.response.status_code if exc.response is not None else "unknown"
                errors.append(f"{candidate_model} attempt {attempt}: http_{status}")
                if isinstance(status, int) and status >= 500:
                    # Fast-fail to next model when backend/model returns server errors.
                    break
            except Exception as exc:
                errors.append(f"{candidate_model} attempt {attempt}: {exc}")

            await asyncio.sleep(min(1.2 * attempt, 3.0))

        if content and len(content.strip()) >= 4:
            break

    if not content or len(content.strip()) < 4:
        return {
            "ok": True,
            "path": rel_path,
            "content": _emergency_content(rel_path),
            "specialist": domain,
            "model": used_model,
            "fallback": "emergency_template",
            "errors": errors,
        }

    return {
        "ok": True,
        "path": rel_path,
        "content": content,
        "specialist": domain,
        "model": used_model,
    }


async def stream_specialist_generation(
    files: List[Dict[str, Any]],
    plan: Dict[str, Any],
    task: str,
    project_path: str,
) -> AsyncGenerator[Dict[str, Any], None]:
    project_name = str(plan.get("project_name", "Project"))

    for idx, file_spec in enumerate(files, start=1):
        path = str(file_spec.get("path", ""))
        domain = str(file_spec.get("specialist", "backend"))
        yield {
            "type": "log",
            "data": {
                "phase": "specialist_start",
                "message": f"Generating ({idx}/{len(files)}): {path}",
                "path": path,
                "specialist": domain,
            },
        }

        try:
            result = await run_specialist(
                domain=domain,
                file_spec=file_spec,
                project_name=project_name,
                task=task,
                project_path=project_path,
                context_blobs=[],
            )
        except Exception as exc:
            result = {
                "ok": True,
                "path": path,
                "content": _emergency_content(path),
                "specialist": domain,
                "model": "fallback",
                "fallback": "emergency_template",
                "errors": [str(exc)],
            }

        if not result.get("ok"):
            result = {
                "ok": True,
                "path": path,
                "content": _emergency_content(path),
                "specialist": domain,
                "model": "fallback",
                "fallback": "emergency_template",
                "errors": [str(result.get("error", "unknown"))],
            }

        content = str(result.get("content") or "")
        if not content.strip():
            content = _emergency_content(path)
            result["content"] = content

        if not content.strip():
            yield {
                "type": "error",
                "data": {
                    "message": f"Specialist failed for {path}: missing fallback content",
                    "path": path,
                    "specialist": domain,
                },
            }
            continue

        if result.get("fallback") == "emergency_template":
            yield {
                "type": "log",
                "data": {
                    "phase": "specialist_fallback",
                    "message": f"Used emergency template for {path} after model failures.",
                    "path": path,
                    "specialist": domain,
                },
            }

        yield {
            "type": "file_stream",
            "data": {
                "path": path,
                "delta": content,
                "specialist": domain,
            },
        }
        yield {
            "type": "specialist_file",
            "data": {
                "path": path,
                "content": content,
                "specialist": domain,
                "model": result.get("model"),
            },
        }
